services:
  bot:
    build:
      context: "."
      dockerfile: "Dockerfile"
    container_name: "vilbot"
    environment:
      DISCORD_TOKEN: "${DISCORD_TOKEN}"
      LOG_LEVEL: "${LOG_LEVEL}"
      DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: "unless-stopped"

  db:
    image: postgres:16
    container_name: "postgres"
    environment:
      POSTGRES_DB: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  postgres_data:
